name: upload-files-to-S3
on:
  push:
jobs:
  upload-sample-file:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code to treat files
        uses: actions/checkout@v2
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Upload to S3
        run: aws s3 cp sample.txt s3://${{ secrets.BUCKET_NAME }}/${{ secrets.BUCKET_DIR }}/sample_${{ github.sha }}.txt