name: upload-files-to-S3
on:
  push:
jobs:
  upload-sample-file:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref_name == 'main' && 'production' || github.ref_name == 'develop' && 'develop' || 'others' }}
    env:
      TZ: 'Asia/Tokyo'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check Secrets are available
        run: |
          if [ -z "${{ secrets.AWS_REGION }}" ]; then
            echo "AWS_REGION is empty"
            exit 1
          fi
          if [ -z "${{ secrets.AWS_ROLE_TO_ASSUME }}" ]; then
            echo "AWS_ROLE_TO_ASSUME is empty"
            exit 1
          fi
      - name: Checkout code to treat files
        uses: actions/checkout@v4
      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Upload to S3
        run: aws s3 cp sample.txt s3://${{ secrets.BUCKET_NAME }}/${{ secrets.BUCKET_DIR }}/$(date +'%Y-%m-%d_%H-%M-%S')/sample_${{ github.sha }}.txt
